<?php
/**
 * CakePHP SeoController
 * @author Eric
 */
App::uses('AppController', 'Controller');

class SeoController extends AppController {
    
    public $name = 'Seo';
    
    public function index(){
        
    }
    
    public function sitemap(){
	
    }
    
    public function robots(){
	$this->autoRender = false;
	echo '# robots.txt generated by http://www.highoctanebrands.com
	User-agent: *
	Disallow: 
	Crawl-delay: 5
	Disallow: /cgi-bin/
	Disallow: /admin/
	Sitemap: http://'.$_SERVER['SERVER_NAME'].'/sitemap';
    }
    
}
