<?php
/**
 * CakePHP SeoController
 * @author Eric
 */
App::uses('AppController', 'Controller');

class SeoController extends AppController {
    
    public $name = 'Seo';
    
    public function beforeFilter() {
	parent::beforeFilter();
	$this->Auth->allow();
    }
    
    public function index(){
        
    }
    
    public function sitemap(){
	
    }
    
    public function robots(){
	$this->autoRender = false;
	echo "# robots.txt generated by http://www.highoctanebrands.com \n";
	echo "User-agent: * \n";
	echo "Disallow:  \n";
	echo "Crawl-delay: 5 \n";
	echo "Disallow: /cgi-bin/ \n";
	echo "Disallow: /admin/ \n";
	echo "Sitemap: http://".$_SERVER['SERVER_NAME']."/sitemap \n";
    }
    
}
